version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    links:
      - php
    networks:
      - sistemaapi

  php:
    image: php:7.2-fpm
    container_name: php
    restart: always
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - sistemaapi

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - sistemaapi

  frontend_vuejs:
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile
    volumes:
      - ./frontend-vue:/app
    ports:
      - 80:80
    working_dir: /app
    command: sh -c "npm install && npm run serve -- --port 80"

networks:
  sistemaapi:
    driver: bridge