version: '3.7'

services:
  frontend_vuejs:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    working_dir: /app
    command: sh -c "npm install && npm run serve"
